# <center><strong>project title</strong></center>

#### **By Mohamed Jamyl**

http://linkedin.com/in/mohamed-jamyl

https://www.kaggle.com/mohamedjamyl

https://github.com/Mohamed-Jamyl

-------------------------

In [15]:
# from IPython.display import Image
# Image(filename='sp.png')

--------------------------------
--------------------------------
--------------------------------

In [16]:
import pandas as pd
import urllib
from sqlalchemy import create_engine


SERVER = '127.0.0.1,1433'  
DATABASE = 'AdventureWorks2022'
USERNAME = 'sa'
PASSWORD = 'Simo.1234'  

params = urllib.parse.quote_plus(
    f"DRIVER={{SQL Server}};"
    f"SERVER={SERVER};"
    f"DATABASE={DATABASE};"
    f"UID={USERNAME};"
    f"PWD={PASSWORD};"
)

engine = create_engine(f"mssql+pyodbc:///?odbc_connect={params}")

query = "SELECT TOP 5 * FROM Sales.SalesOrderHeader;"
df = pd.read_sql(query, engine)


print(df.head())

   SalesOrderID  RevisionNumber  OrderDate    DueDate   ShipDate  Status  \
0         43659               8 2011-05-31 2011-06-12 2011-06-07       5
1         43660               8 2011-05-31 2011-06-12 2011-06-07       5
2         43661               8 2011-05-31 2011-06-12 2011-06-07       5
3         43662               8 2011-05-31 2011-06-12 2011-06-07       5
4         43663               8 2011-05-31 2011-06-12 2011-06-07       5

   OnlineOrderFlag SalesOrderNumber PurchaseOrderNumber   AccountNumber  ...  \
0            False          SO43659         PO522145787  10-4020-000676  ...
1            False          SO43660       PO18850127500  10-4020-000117  ...
2            False          SO43661       PO18473189620  10-4020-000442  ...
3            False          SO43662       PO18444174044  10-4020-000227  ...
4            False          SO43663       PO18009186470  10-4020-000510  ...

   CreditCardID  CreditCardApprovalCode  CurrencyRateID    SubTotal  \
0         16281           105041Vi84182             NaN  20565.6206
1          5618           115213Vi29411             NaN   1294.2529
2          1346             85274Vi6854             4.0  32726.4786
3         10456           125295Vi53935             4.0  28832.5289
4          4322            45303Vi22691             NaN    419.4589

      TaxAmt   Freight    TotalDue Comment  \
0  1971.5149  616.0984  23153.2339    None
1   124.2483   38.8276   1457.3288    None
2  3153.7696  985.5530  36865.8012    None
3  2775.1646  867.2389  32474.9324    None
4    40.2681   12.5838    472.3108    None

                                rowguid  ModifiedDate
0  79B65321-39CA-4115-9CBA-8FE0903E12E6    2011-06-07
1  738DC42D-D03B-48A1-9822-F95A67EA7389    2011-06-07
2  D91B9131-18A4-4A11-BC3A-90B6F53E9D74    2011-06-07
3  4A1ECFC0-CC3A-4740-B028-1C50BB48711C    2011-06-07
4  9B1E7A40-6AE0-4AD3-811C-A64951857C4B    2011-06-07

[5 rows x 26 columns]

In [17]:
query1 = "SELECT * FROM Sales.SalesOrderHeader;"
df = pd.read_sql(query1, engine)
df

,SalesOrderID,RevisionNumber,OrderDate,DueDate,ShipDate,Status,OnlineOrderFlag,SalesOrderNumber,PurchaseOrderNumber,AccountNumber,...,CreditCardID,CreditCardApprovalCode,CurrencyRateID,SubTotal,TaxAmt,Freight,TotalDue,Comment,rowguid,ModifiedDate
0,43659,8,2011-05-31,2011-06-12,2011-06-07,5,False,SO43659,PO522145787,10-4020-000676,...,16281.0,105041Vi84182,NaN,20565.6206,1971.5149,616.0984,23153.2339,None,79B65321-39CA-4115-9CBA-8FE0903E12E6,2011-06-07
1,43660,8,2011-05-31,2011-06-12,2011-06-07,5,False,SO43660,PO18850127500,10-4020-000117,...,5618.0,115213Vi29411,NaN,1294.2529,124.2483,38.8276,1457.3288,None,738DC42D-D03B-48A1-9822-F95A67EA7389,2011-06-07
2,43661,8,2011-05-31,2011-06-12,2011-06-07,5,False,SO43661,PO18473189620,10-4020-000442,...,1346.0,85274Vi6854,4.0,32726.4786,3153.7696,985.5530,36865.8012,None,D91B9131-18A4-4A11-BC3A-90B6F53E9D74,2011-06-07
3,43662,8,2011-05-31,2011-06-12,2011-06-07,5,False,SO43662,PO18444174044,10-4020-000227,...,10456.0,125295Vi53935,4.0,28832.5289,2775.1646,867.2389,32474.9324,None,4A1ECFC0-CC3A-4740-B028-1C50BB48711C,2011-06-07
4,43663,8,2011-05-31,2011-06-12,2011-06-07,5,False,SO43663,PO18009186470,10-4020-000510,...,4322.0,45303Vi22691,NaN,419.4589,40.2681,12.5838,472.3108,None,9B1E7A40-6AE0-4AD3-811C-A64951857C4B,2011-06-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31460,75119,8,2014-06-30,2014-07-12,2014-07-07,5,True,SO75119,None,10-4030-011981,...,6761.0,429826Vi35166,NaN,42.2800,3.3824,1.0570,46.7194,None,9382F1C9-383A-435F-9449-0EECEA21B78D,2014-07-07
31461,75120,8,2014-06-30,2014-07-12,2014-07-07,5,True,SO75120,None,10-4030-018749,...,8925.0,929849Vi46003,NaN,84.9600,6.7968,2.1240,93.8808,None,AE6A4FCF-FF73-4CD4-AF2C-5993D00D4AFE,2014-07-07
31462,75121,8,2014-06-30,2014-07-12,2014-07-07,5,True,SO75121,None,10-4030-015251,...,14220.0,529864Vi73738,NaN,74.9800,5.9984,1.8745,82.8529,None,D7395C0E-00CB-4BFA-A238-0D6A9F49884F,2014-07-07
31463,75122,8,2014-06-30,2014-07-12,2014-07-07,5,True,SO75122,None,10-4030-015868,...,18719.0,330022Vi97312,NaN,30.9700,2.4776,0.7743,34.2219,None,4221035A-4159-492F-AF40-4363A64FFC16,2014-07-07
31464,75123,8,2014-06-30,2014-07-12,2014-07-07,5,True,SO75123,None,10-4030-018759,...,10084.0,230370Vi51970,NaN,189.9700,15.1976,4.7493,209.9169,None,D54752FF-2B54-4BE5-95EA-3B72289C059F,2014-07-07

In [18]:
query2 = "SELECT * FROM Sales.SalesOrderDetail;"
df2 = pd.read_sql(query2, engine)
df2

,SalesOrderID,SalesOrderDetailID,CarrierTrackingNumber,OrderQty,ProductID,SpecialOfferID,UnitPrice,UnitPriceDiscount,LineTotal,rowguid,ModifiedDate
0,43659,1,4911-403C-98,1,776,1,2024.994,0.0,2024.994,B207C96D-D9E6-402B-8470-2CC176C42283,2011-05-31
1,43659,2,4911-403C-98,3,777,1,2024.994,0.0,6074.982,7ABB600D-1E77-41BE-9FE5-B9142CFC08FA,2011-05-31
2,43659,3,4911-403C-98,1,778,1,2024.994,0.0,2024.994,475CF8C6-49F6-486E-B0AD-AFC6A50CDD2F,2011-05-31
3,43659,4,4911-403C-98,1,771,1,2039.994,0.0,2039.994,04C4DE91-5815-45D6-8670-F462719FBCE3,2011-05-31
4,43659,5,4911-403C-98,1,772,1,2039.994,0.0,2039.994,5A74C7D2-E641-438E-A7AC-37BF23280301,2011-05-31
...,...,...,...,...,...,...,...,...,...,...,...
121312,75122,121313,None,1,878,1,21.980,0.0,21.980,8CAD6675-18CC-4F47-8287-97B41A8EE47D,2014-06-30
121313,75122,121314,None,1,712,1,8.990,0.0,8.990,84F1C363-1C50-4442-BE16-541C59B6E12C,2014-06-30
121314,75123,121315,None,1,878,1,21.980,0.0,21.980,C18B6476-429F-4BB1-828E-2BE5F82A0A51,2014-06-30
121315,75123,121316,None,1,879,1,159.000,0.0,159.000,75A89C6A-C60A-47EA-8A52-B52A9C435B64,2014-06-30
121316,75123,121317,None,1,712,1,8.990,0.0,8.990,73646D26-0461-450D-8019-2C6C858619CA,2014-06-30

In [19]:
query3 = "SELECT * FROM Production.Product;"
df3 = pd.read_sql(query3, engine)
df3

,ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,...,ProductLine,Class,Style,ProductSubcategoryID,ProductModelID,SellStartDate,SellEndDate,DiscontinuedDate,rowguid,ModifiedDate
0,1,Adjustable Race,AR-5381,False,False,None,1000,750,0.0000,0.00,...,None,None,None,NaN,NaN,2008-04-30,NaT,None,694215B7-08F7-4C0D-ACB1-D734BA44C0C8,2014-02-08 10:01:36.827
1,2,Bearing Ball,BA-8327,False,False,None,1000,750,0.0000,0.00,...,None,None,None,NaN,NaN,2008-04-30,NaT,None,58AE3C20-4F3A-4749-A7D4-D568806CC537,2014-02-08 10:01:36.827
2,3,BB Ball Bearing,BE-2349,True,False,None,800,600,0.0000,0.00,...,None,None,None,NaN,NaN,2008-04-30,NaT,None,9C21AED2-5BFA-4F18-BCB8-F11638DC2E4E,2014-02-08 10:01:36.827
3,4,Headset Ball Bearings,BE-2908,False,False,None,800,600,0.0000,0.00,...,None,None,None,NaN,NaN,2008-04-30,NaT,None,ECFED6CB-51FF-49B5-B06C-7D8AC834DB8B,2014-02-08 10:01:36.827
4,316,Blade,BL-2036,True,False,None,800,600,0.0000,0.00,...,None,None,None,NaN,NaN,2008-04-30,NaT,None,E73E9750-603B-4131-89F5-3DD15ED5FF80,2014-02-08 10:01:36.827
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499,995,ML Bottom Bracket,BB-8107,True,True,None,500,375,44.9506,101.24,...,None,M,None,5.0,96.0,2013-05-30,NaT,None,71AB847F-D091-42D6-B735-7B0C2D82FC84,2014-02-08 10:01:36.827
500,996,HL Bottom Bracket,BB-9108,True,True,None,500,375,53.9416,121.49,...,None,H,None,5.0,97.0,2013-05-30,NaT,None,230C47C5-08B2-4CE3-B706-69C0BDD62965,2014-02-08 10:01:36.827
501,997,"Road-750 Black, 44",BK-R19B-44,True,True,Black,100,75,343.6496,539.99,...,R,L,U,2.0,31.0,2013-05-30,NaT,None,44CE4802-409F-43AB-9B27-CA53421805BE,2014-02-08 10:01:36.827
502,998,"Road-750 Black, 48",BK-R19B-48,True,True,Black,100,75,343.6496,539.99,...,R,L,U,2.0,31.0,2013-05-30,NaT,None,3DE9A212-1D49-40B6-B10A-F564D981DBDE,2014-02-08 10:01:36.827
503,999,"Road-750 Black, 52",BK-R19B-52,True,True,Black,100,75,343.6496,539.99,...,R,L,U,2.0,31.0,2013-05-30,NaT,None,AE638923-2B67-4679-B90E-ABBAB17DCA31,2014-02-08 10:01:36.827

In [20]:
query4 = "SELECT * FROM Sales.Store;"
df4 = pd.read_sql(query4, engine)
df4

,BusinessEntityID,Name,SalesPersonID,Demographics,rowguid,ModifiedDate
0,292,Next-Door Bike Store,279,"<StoreSurvey xmlns=""http://schemas.microsoft.c...",A22517E3-848D-4EBE-B9D9-7437F3432304,2014-09-12 11:15:07.497
1,294,Professional Sales and Service,276,"<StoreSurvey xmlns=""http://schemas.microsoft.c...",B50CA50B-C601-4A13-B07E-2C63862D71B4,2014-09-12 11:15:07.497
2,296,Riders Company,277,"<StoreSurvey xmlns=""http://schemas.microsoft.c...",337C3688-1339-4E1A-A08A-B54B23566E49,2014-09-12 11:15:07.497
3,298,The Bike Mechanics,275,"<StoreSurvey xmlns=""http://schemas.microsoft.c...",7894F278-F0C8-4D16-BD75-213FDBF13023,2014-09-12 11:15:07.497
4,300,Nationwide Supply,286,"<StoreSurvey xmlns=""http://schemas.microsoft.c...",C3FC9705-A8C4-4F3A-9550-EB2FA4B7B64D,2014-09-12 11:15:07.497
...,...,...,...,...,...,...
696,1988,Retreat Inn,282,"<StoreSurvey xmlns=""http://schemas.microsoft.c...",EA21EC81-1BFA-4A07-9B4D-73D9852AFCBF,2014-09-12 11:15:07.497
697,1990,Technical Parts Manufacturing,281,"<StoreSurvey xmlns=""http://schemas.microsoft.c...",C8E3C4ED-8F58-4DB2-B600-E0CD11D9CFAD,2014-09-12 11:15:07.497
698,1992,Totes & Baskets Company,277,"<StoreSurvey xmlns=""http://schemas.microsoft.c...",CE860B58-643C-4567-BFD8-06E97969CC67,2014-09-12 11:15:07.497
699,1994,World of Bikes,277,"<StoreSurvey xmlns=""http://schemas.microsoft.c...",0C10F2B6-A13A-440C-9C25-5B28D482872A,2014-09-12 11:15:07.497
700,2051,A Bicycle Association,275,"<StoreSurvey xmlns=""http://schemas.microsoft.c...",82237172-D3FE-4A95-82EF-636F655240AD,2014-09-12 11:15:07.497

In [21]:
df4['Name'].value_counts()

Name
Sports Products Store                  2
Friendly Bike Shop                     2
Next-Door Bike Store                   1
Road Way Sales and Rental              1
Beneficial Exercises and Activities    1
                                      ..
Handy Bike Services                    1
Fashionable Bikes and Accessories      1
Extreme Toy Store                      1
Citywide Service and Repair            1
A Bicycle Association                  1
Name: count, Length: 699, dtype: int64

In [22]:
query5 = "SELECT * FROM Sales.Customer;"
df5 = pd.read_sql(query5, engine)
df5

,CustomerID,PersonID,StoreID,TerritoryID,AccountNumber,rowguid,ModifiedDate
0,1,NaN,934.0,1,AW00000001,3F5AE95E-B87D-4AED-95B4-C3797AFCB74F,2014-09-12 11:15:07.263
1,2,NaN,1028.0,1,AW00000002,E552F657-A9AF-4A7D-A645-C429D6E02491,2014-09-12 11:15:07.263
2,3,NaN,642.0,4,AW00000003,130774B1-DB21-4EF3-98C8-C104BCD6ED6D,2014-09-12 11:15:07.263
3,4,NaN,932.0,4,AW00000004,FF862851-1DAA-4044-BE7C-3E85583C054D,2014-09-12 11:15:07.263
4,5,NaN,1026.0,4,AW00000005,83905BDC-6F5E-4F71-B162-C98DA069F38A,2014-09-12 11:15:07.263
...,...,...,...,...,...,...,...
19815,30114,1985.0,1986.0,7,AW00030114,97154F3D-28F1-4B15-AE03-9518B781ECE3,2014-09-12 11:15:07.263
19816,30115,1987.0,1988.0,6,AW00030115,E4CF8FD5-30A4-4B8E-8FD8-47032E255778,2014-09-12 11:15:07.263
19817,30116,1989.0,1990.0,4,AW00030116,EC409609-D25D-41B8-9D15-A1AA6E89FC77,2014-09-12 11:15:07.263
19818,30117,1991.0,1992.0,4,AW00030117,6F08E2FB-1CD3-4F6E-A2E6-385669598B19,2014-09-12 11:15:07.263
19819,30118,1993.0,1994.0,3,AW00030118,2495B4EB-FE8B-459E-A1B6-DBA25C04E626,2014-09-12 11:15:07.263

In [23]:
df3

,ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,...,ProductLine,Class,Style,ProductSubcategoryID,ProductModelID,SellStartDate,SellEndDate,DiscontinuedDate,rowguid,ModifiedDate
0,1,Adjustable Race,AR-5381,False,False,None,1000,750,0.0000,0.00,...,None,None,None,NaN,NaN,2008-04-30,NaT,None,694215B7-08F7-4C0D-ACB1-D734BA44C0C8,2014-02-08 10:01:36.827
1,2,Bearing Ball,BA-8327,False,False,None,1000,750,0.0000,0.00,...,None,None,None,NaN,NaN,2008-04-30,NaT,None,58AE3C20-4F3A-4749-A7D4-D568806CC537,2014-02-08 10:01:36.827
2,3,BB Ball Bearing,BE-2349,True,False,None,800,600,0.0000,0.00,...,None,None,None,NaN,NaN,2008-04-30,NaT,None,9C21AED2-5BFA-4F18-BCB8-F11638DC2E4E,2014-02-08 10:01:36.827
3,4,Headset Ball Bearings,BE-2908,False,False,None,800,600,0.0000,0.00,...,None,None,None,NaN,NaN,2008-04-30,NaT,None,ECFED6CB-51FF-49B5-B06C-7D8AC834DB8B,2014-02-08 10:01:36.827
4,316,Blade,BL-2036,True,False,None,800,600,0.0000,0.00,...,None,None,None,NaN,NaN,2008-04-30,NaT,None,E73E9750-603B-4131-89F5-3DD15ED5FF80,2014-02-08 10:01:36.827
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499,995,ML Bottom Bracket,BB-8107,True,True,None,500,375,44.9506,101.24,...,None,M,None,5.0,96.0,2013-05-30,NaT,None,71AB847F-D091-42D6-B735-7B0C2D82FC84,2014-02-08 10:01:36.827
500,996,HL Bottom Bracket,BB-9108,True,True,None,500,375,53.9416,121.49,...,None,H,None,5.0,97.0,2013-05-30,NaT,None,230C47C5-08B2-4CE3-B706-69C0BDD62965,2014-02-08 10:01:36.827
501,997,"Road-750 Black, 44",BK-R19B-44,True,True,Black,100,75,343.6496,539.99,...,R,L,U,2.0,31.0,2013-05-30,NaT,None,44CE4802-409F-43AB-9B27-CA53421805BE,2014-02-08 10:01:36.827
502,998,"Road-750 Black, 48",BK-R19B-48,True,True,Black,100,75,343.6496,539.99,...,R,L,U,2.0,31.0,2013-05-30,NaT,None,3DE9A212-1D49-40B6-B10A-F564D981DBDE,2014-02-08 10:01:36.827
503,999,"Road-750 Black, 52",BK-R19B-52,True,True,Black,100,75,343.6496,539.99,...,R,L,U,2.0,31.0,2013-05-30,NaT,None,AE638923-2B67-4679-B90E-ABBAB17DCA31,2014-02-08 10:01:36.827

In [24]:
query6 = """SELECT 
                ISNULL(st.Name, 'Online Customer') AS Store_or_channel,
                -- p.Name AS Product,
                ISNULL(p2.Name, 'Uncategorized') AS Category,
                ISNULL(p1.Name, 'Uncategorized') AS SubCategory,
                ISNULL(p.Color, 'N/A') AS Color,
                p.StandardCost AS Cost,
                d.OrderQty AS Quantity,
                d.UnitPrice,
                d.UnitPriceDiscount,
                d.LineTotal AS Revenue,
                (d.LineTotal - (d.OrderQty * p.StandardCost)) AS Profit,
                YEAR(h.OrderDate) AS Order_year,
                MONTH(h.OrderDate) AS Order_month,
                DATENAME(MONTH, h.OrderDate) AS Order_month_name,
                DATENAME(WEEKDAY, h.OrderDate) AS Order_day_name,
                DATEDIFF(DAY, h.OrderDate, h.ShipDate) AS Process_days_to_ship,
                DATEDIFF(DAY, h.DueDate, h.ShipDate) AS Delivery_delay_days, 
                p.ReorderPoint AS Reorder_point

            FROM Sales.SalesOrderDetail d
            INNER JOIN Sales.SalesOrderHeader h 
                ON d.SalesOrderID = h.SalesOrderID
            INNER JOIN Production.Product p 
                ON d.ProductID = p.ProductID
            LEFT JOIN Production.ProductSubcategory p1 
                ON p.ProductSubcategoryID = p1.ProductSubcategoryID
            LEFT JOIN Production.ProductCategory p2 
                ON p1.ProductCategoryID = p2.ProductCategoryID
            LEFT JOIN Sales.Customer c 
                ON h.CustomerID = c.CustomerID
            LEFT JOIN Sales.Store st 
                ON c.StoreID = st.BusinessEntityID;
    """

df6 = pd.read_sql(query6, engine)

In [25]:
df6

,Store_or_channel,Category,SubCategory,Color,Cost,Quantity,UnitPrice,UnitPriceDiscount,Revenue,Profit,Order_year,Order_month,Order_month_name,Order_day_name,Process_days_to_ship,Delivery_delay_days,Reorder_point
0,Better Bike Shop,Bikes,Mountain Bikes,Black,1898.0944,1,2024.994,0.0,2024.994,126.8996,2011,5,May,Tuesday,7,-5,75
1,Better Bike Shop,Bikes,Mountain Bikes,Black,1898.0944,3,2024.994,0.0,6074.982,380.6988,2011,5,May,Tuesday,7,-5,75
2,Better Bike Shop,Bikes,Mountain Bikes,Black,1898.0944,1,2024.994,0.0,2024.994,126.8996,2011,5,May,Tuesday,7,-5,75
3,Better Bike Shop,Bikes,Mountain Bikes,Silver,1912.1544,1,2039.994,0.0,2039.994,127.8396,2011,5,May,Tuesday,7,-5,75
4,Better Bike Shop,Bikes,Mountain Bikes,Silver,1912.1544,1,2039.994,0.0,2039.994,127.8396,2011,5,May,Tuesday,7,-5,75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121312,Online Customer,Accessories,Fenders,N/A,8.2205,1,21.980,0.0,21.980,13.7595,2014,6,June,Monday,7,-5,3
121313,Online Customer,Clothing,Caps,Multi,6.9223,1,8.990,0.0,8.990,2.0677,2014,6,June,Monday,7,-5,3
121314,Online Customer,Accessories,Fenders,N/A,8.2205,1,21.980,0.0,21.980,13.7595,2014,6,June,Monday,7,-5,3
121315,Online Customer,Accessories,Bike Stands,N/A,59.4660,1,159.000,0.0,159.000,99.5340,2014,6,June,Monday,7,-5,3
121316,Online Customer,Clothing,Caps,Multi,6.9223,1,8.990,0.0,8.990,2.0677,2014,6,June,Monday,7,-5,3

In [ ]:
df6['UnitPrice'] = df6['UnitPrice'].apply(lambda x : round(x,2))
df6['Revenue'] = df6['Revenue'].apply(lambda x : round(x,2))
df6['Profit'] = df6['Profit'].apply(lambda x : round(x,2))
df6['Cost'] = df6['Cost'].apply(lambda x : round(x,2))

In [41]:
df6['Delivery_delay_days'] = df6['Delivery_delay_days'].apply(lambda x : -(x))

In [ ]:
df6['Order_day_name'].value_counts()

Order_day_name
Wednesday    20249
Monday       19799
Saturday     18150
Thursday     16927
Tuesday      16638
Sunday       16371
Friday       13183
Name: count, dtype: int64

In [ ]:
df6['Store_or_channel'].value_counts()

Store_or_channel
Online Customer                       60398
Vigorous Exercise Company               530
Larger Cycle Shop                       482
Retail Mall                             451
Rapid Bikes                             446
                                      ...
Retail Cycle Shop                         1
Imported and Domestic Cycles              1
Recreation Supplies                       1
Chain and Chain Tool Distributions        1
Seats and Saddles Company                 1
Name: count, Length: 634, dtype: int64

In [ ]:
def store(a):
    if a == 'Online Customer':
        return 'Online Customer'
    else :
        return 'Stores / Resellers'

df6['Store_or_channel2'] = df6['Store_or_channel'].apply(lambda x : store(x))

In [ ]:
df6['Store_or_channel2'].value_counts()

Store_or_channel2
Stores / Resellers    60919
Online Customer       60398
Name: count, dtype: int64

In [ ]:
c

-------------------------

----------------------------------


# <center><strong>Conclusion</strong></center>
--------------------------------------------
#### ****

---------------------------------------

In [ ]:
# !jupyter nbconvert --to html "filename.ipynb"